/** Cities, regions, and countries for location typeahead (admin add + UX hints). */
export const LOCATION_SUGGESTIONS: string[] = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Austin",
  "Azerbaijan",
  "Bangalore",
  "Bangladesh",
  "Barcelona",
  "Beijing",
  "Belgium",
  "Berlin",
  "Bolivia",
  "Boston",
  "Brazil",
  "Bulgaria",
  "Cairo",
  "California",
  "Canada",
  "Chile",
  "China",
  "Chennai",
  "Chicago",
  "Colombia",
  "Copenhagen",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Dallas",
  "Delhi",
  "Denmark",
  "Detroit",
  "Dubai",
  "Dublin",
  "Ecuador",
  "Egypt",
  "Estonia",
  "Ethiopia",
  "Finland",
  "France",
  "Frankfurt",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Houston",
  "Hungary",
  "Hyderabad",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jakarta",
  "Japan",
  "Johannesburg",
  "Jordan",
  "Kansas City",
  "Kenya",
  "Kolkata",
  "Kuwait",
  "Las Vegas",
  "Latvia",
  "Lebanon",
  "Lisbon",
  "Lithuania",
  "London",
  "Los Angeles",
  "Luxembourg",
  "Madrid",
  "Malaysia",
  "Malta",
  "Manchester",
  "Melbourne",
  "Mexico",
  "Miami",
  "Michigan",
  "Milan",
  "Minneapolis",
  "Mumbai",
  "Munich",
  "Nairobi",
  "Nepal",
  "Netherlands",
  "New Delhi",
  "New York",
  "New Zealand",
  "Nigeria",
  "Norway",
  "Ohio",
  "Oman",
  "Osaka",
  "Pakistan",
  "Panama",
  "Paris",
  "Peru",
  "Philadelphia",
  "Philippines",
  "Phoenix",
  "Poland",
  "Portland",
  "Portugal",
  "Prague",
  "Puerto Rico",
  "Qatar",
  "Quebec",
  "Romania",
  "Rome",
  "Russia",
  "San Diego",
  "San Francisco",
  "Saudi Arabia",
  "Seattle",
  "Seoul",
  "Serbia",
  "Shanghai",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "Stockholm",
  "Sudan",
  "Sweden",
  "Switzerland",
  "Sydney",
  "Taiwan",
  "Tanzania",
  "Texas",
  "Thailand",
  "Tokyo",
  "Toronto",
  "Tunisia",
  "Turkey",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Utah",
  "Vancouver",
  "Venezuela",
  "Vienna",
  "Vietnam",
  "Virginia",
  "Warsaw",
  "Washington",
  "Washington DC",
  "Zimbabwe",
  "Zurich",
];

export function filterLocationSuggestions(query: string, pool: string[], limit = 15): string[] {
  const q = query.trim().toLowerCase();
  if (!q) {
    return pool.slice(0, limit);
  }
  return pool
    .filter((name) => name.toLowerCase().includes(q))
    .sort((a, b) => {
      const al = a.toLowerCase();
      const bl = b.toLowerCase();
      const aStarts = al.startsWith(q);
      const bStarts = bl.startsWith(q);
      if (aStarts !== bStarts) return aStarts ? -1 : 1;
      return al.localeCompare(bl);
    })
    .slice(0, limit);
}
